document.writeln("<style>");
document.writeln("body{font-size:12px;}");
document.writeln("form{border:0px;padding:0px;margin:0px;}");
document.writeln(".floorbody{width:981px;height:108px;background:#FAFAFD;padding:1px 0px 1px 0px;margin:auto;}");
document.writeln(".floorleft{width:135px;height:108px;float:left;background:#F5F5FE;text-align:center;}");
document.writeln(".floorright{width:800px;height:108px;float:right;text-align:left;padding-left:18px;}");
document.writeln(".floorselect{height:40px;font-size:14px;font-weight:bold;padding-top:6px;}");
document.writeln(".floorleft1{float:left;width:210px;padding-top:7px;font-size:14px;}");
document.writeln(".floorright1{float:left;}");
document.writeln(".floordan{margin-top:1px;height:27px;width:85px;color:#545454;font-size:14px;font-weight:bold;padding-top:2px;border-bottom:#969696 1px solid;border-right:#969696 1px solid;}");
document.writeln(".floortext{width:300px;height:21px;}");
document.writeln(".floorlinks{width:100%;height:20px;}");
document.writeln(".floorlinks a:link,.floorlinks a:visited{text-decoration:none;color:#222222;}");
document.writeln(".floorlinks a:active,.floorlinks a:hover{text-decoration:underline;color:red;}");
document.writeln(".floordownlink{width:100%;height:26px;background:#E2E2F0;color:#000000;text-align:left;line-height:26px;}");
document.writeln(".floordownlink a:link,.floordownlink a:visited{text-decoration:none;color:#000000;}");
document.writeln(".floordownlink a:active,.floordownlink a:hover{text-decoration:underline;color:red;}");
document.writeln(".floorleft2{float:left;padding-top:3px;padding-left:10px;text-align:left;}");
document.writeln(".floorright2{float:right;text-align:right;padding-top:3px;padding-right:10px;}");
document.writeln(".floorright2 a:link,.floorright2 a:visited{text-decoration:underline;color:#000000;}");
document.writeln(".floorright2 a:active,.floorright2 a:hover{text-decoration:underline;color:#000000;}");
document.writeln(".floorbottom{text-align:center;width:776px;float:left;margin:auto}");
document.writeln(".floorbottomleft{float:left;text-align:right;width:110px;padding-right:10px;}");
document.writeln(".floorbottomright{float:right;text-align:left;padding-top:5px;line-height:20px;}");
document.writeln(".floorbottom a:link,.floorbottom a:visited{text-decoration:none;color:#222222;}");
document.writeln(".floorbottom a:active,.floorbottom a:hover{text-decoration:underline;color:red;}");
document.writeln(".floor776{width:776px;text-align:center;margin:auto}");
document.writeln(".floor1003{width:981px;text-align:center;margin:auto}");
document.writeln("</style>");

document.writeln("<div class=floorbody>");
document.writeln("<div class=floorleft><a href=http://www.yesky.com><img src=http://image.yesky.com/TLimages/newmobile/ylogo.gif border=\"0\"/></a></div>");
document.writeln("<div class=floorright>");
document.writeln("<div class=floorselect>");
document.writeln("<div class=floorleft1>更多精彩资讯尽在天极IT搜索</div>");
document.writeln("<div class=floorright1>");
document.writeln("<form name=search action=http://search.yesky.com/search.do>");
document.writeln("<INPUT TYPE=text NAME=wd class=floortext>　<INPUT TYPE=submit VALUE=天极搜索 NAME=btnsearch class=floordan>");
document.writeln("</form>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div class=floorlinks>");
document.writeln("<b><a href=http://www.chinabyte.com/>天极Chinabyte</a>:</b> ");
document.writeln("<a href=http://news.chinabyte.com/>新闻</a> <a href=http://column.chinabyte.com/>评论</a> ");
document.writeln("<a href=http://telecom.chinabyte.com/>通信</a> <a href=http://net.chinabyte.com/>互联网</a>");
document.writeln("<a href=http://my.chinabyte.com/>CB博客</a> <a href=http://com.chinabyte.com/>企业博客</a>");
document.writeln("<a href=http://e.chinabyte.com/>信息化</a> <a href=http://soft.chinabyte.com>企业软件</a> ");
document.writeln("<a href=http://solution.chinabyte.com/>解决方案</a> <a href=http://biz.chinabyte.com/>商用系统</a> ");
document.writeln("<a href=http://server.chinabyte.com>服务器</a> <a href=http://data.chinabyte.com//>数据调查</a> ");
document.writeln("</div>");
document.writeln("<div class=floorlinks>");
document.writeln("<b><a href=http://www.yesky.com>天极Yesky</a>: </b>");
document.writeln("<a href=http://product.yesky.com/>产品库</a> <a href=http://www.yesky.com/jxs/>经销商</a>");
document.writeln("<a href=http://cseek.yesky.com/>商情</a> <a href=http://mobile.yesky.com/>手机</a> ");
document.writeln("<a href=http://digital.yesky.com/>数码</a> <a href=http://notebook.yesky.com/>笔记本</a>");
document.writeln("<a href=http://pc.yesky.com>台式机</a> <a href=http://diy.yesky.com>硬件</a>");
document.writeln("<a href=http://oa.yesky.com/>外设</a> <a href=http://net.yesky.com>网络</a>");
document.writeln("<a href=http://dh.yesky.com/>数字家庭</a> <a href=http://lab.yesky.com>评测</a>");
document.writeln("<a href=http://e.yesky.com/>E时代</a> <a href=http://soft.yesky.com/>软件</a>");
document.writeln("<a href=http://game.yesky.com/>游戏</a> <a href=http://www.mydown.com/>下载</a>");
document.writeln("</div>");
document.writeln("<div class=floorlinks>");
document.writeln("<b><a href=http://www.techtarget.com.cn/>IT专家网</a>:</b> ");
document.writeln("<a href=http://searchdatabase.techtarget.com.cn/>数据库</a> <a href=http://searchmobilecomputing.techtarget.com.cn/>移动计算</a> ");
document.writeln("<a href=http://searchnetworking.techtarget.com.cn/>网络</a> <a href=http://searchsecurity.techtarget.com.cn/>安全</a> ");
document.writeln("<a href=http://searchstorage.techtarget.com.cn/>存储</a> <a href=http://searchwebservices.techtarget.com.cn/>Web服务</a>");
document.writeln("<a href=http://searchcio.techtarget.com.cn/>CIO</a> <a href=http://searchsmallbizit.techtarget.com.cn/>中小企业IT</a>");
document.writeln("<a href=http://askexpert.techtarget.com.cn/>IT专家库</a> <a href=http://searchwhitepaper.techtarget.com.cn/>白皮书</a>");
document.writeln("<a href=http://bbs.techtarget.com.cn/>IT专家网论坛</a> <a href=http://club.techtarget.com.cn/>IT专家网社区</a>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div class=floordownlink>");
document.writeln("<div class=floorleft2>");
document.writeln("<a href=http://www.yesky.com/web/tougao.htm>欢迎投稿</a> |");
document.writeln("<a href=http://www.chinabyte.com/service/index.shtm>天极服务</a> |");
document.writeln("<a href=http://www.yesky.com/web/about.htm>关于我们</a> |");
document.writeln("<a href=http://www.yesky.com/web/wzls.htm>网站律师</a> |");
document.writeln("<a href=http://maillist.yesky.com/>电子杂志</a> |");
document.writeln("<a href=http://rss.yesky.com/>RSS订阅</a> |");
document.writeln("<a href=http://link.yesky.com/ onclick=RealAddPortal('22773','2.1')>友情合作</a> |");
document.writeln("<a href=http://www.yesky.com/web/zhaoping.htm>加入我们</a> |");
document.writeln("<a href=http://www.yesky.com/web/website.htm>网站地图</a>");
document.writeln("</div>");
document.writeln("<div class=floorright2>");
document.writeln("<a href=# ONCLICK=this.style.behavior='url(#default#homepage)';this.setHomePage('http://www.yesky.com/');>设定天极为首页</a>");
document.writeln("</div>");
document.writeln("</div>");

document.writeln("<div class=floorbottom>");
document.writeln("<div class=floorbottomleft><a href=http://www.hd315.gov.cn/beian/view.asp?bianhao=0402000103000001><img src=http://www.yesky.com/newimages/index/biaoshi.gif border=0/></a></div>");
document.writeln("<div class=floorbottomright>");
document.writeln("Copyright (C) 1999-2006 Chinabyte.com, All Rights Reserved 版权所有 天极网络");
document.writeln("<a href=http://www.yesky.com/74/1719074.shtml>渝ICP证B2-20030003号</a><br /> ");
document.writeln("商务联系、网站内容、合作建议：010-82657868 ");
document.writeln("<a href=http://www.yesky.com/web/about.htm>详细联系方式</a> ");
document.writeln("<a href=http://feedback.yesky.com/advice/yjb.htm>在线提交意见反馈</a> ");
document.writeln("Powered by 天极内容管理平台CMS4i ");
document.writeln("</div>");
document.writeln("</div>");
